version: "3.3"

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:4.4
    container_name: delivery-radius-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
